apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-default-alertmanager
  annotations:
    policy.open-cluster-management.io/standards: NIST-CSF
    policy.open-cluster-management.io/categories: PR.IP Information Protection Processes and Procedures
    policy.open-cluster-management.io/controls: PR.IP-1 Baseline Configuration
spec:
  remediationAction: inform
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-default-alertmanager
        spec:
          remediationAction: inform
          severity: low
          namespaceSelector:
            exclude:
              - kube-*
            include:
              - default
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: monitoring.coreos.com/v1
                kind: Alertmanager
                metadata:
                  labels:
                    alertmanager: main
                    app.kubernetes.io/component: alert-router
                    app.kubernetes.io/name: alertmanager
                    app.kubernetes.io/part-of: openshift-monitoring
                    app.kubernetes.io/version: 0.22.2
                  name: main
                  namespace: openshift-monitoring
                spec:
                  affinity:
                    podAntiAffinity:
                      preferredDuringSchedulingIgnoredDuringExecution:
                        - podAffinityTerm:
                            labelSelector:
                              matchLabels:
                                app.kubernetes.io/component: alert-router
                                app.kubernetes.io/name: alertmanager
                                app.kubernetes.io/part-of: openshift-monitoring
                            namespaces:
                              - openshift-monitoring
                            topologyKey: kubernetes.io/hostname
                          weight: 100
                  containers:
                    - args:
                        - '-provider=openshift'
                        - '-https-address=:9095'
                        - '-http-address='
                        - '-email-domain=*'
                        - '-upstream=http://localhost:9093'
                        - '-openshift-sar=[{"resource": "namespaces", "verb": "get"}, {"resource": "alertmanagers", "resourceAPIGroup": "monitoring.coreos.com", "namespace": "openshift-monitoring", "verb": "patch", "resourceName": "non-existant"}]'
                        - '-openshift-delegate-urls={"/": {"resource": "namespaces", "verb": "get"}, "/": {"resource":"alertmanagers", "group": "monitoring.coreos.com", "namespace": "openshift-monitoring", "verb": "patch", "name": "non-existant"}}'
                        - '-tls-cert=/etc/tls/private/tls.crt'
                        - '-tls-key=/etc/tls/private/tls.key'
                        - '-client-secret-file=/var/run/secrets/kubernetes.io/serviceaccount/token'
                        - '-cookie-secret-file=/etc/proxy/secrets/session_secret'
                        - '-openshift-service-account=alertmanager-main'
                        - '-openshift-ca=/etc/pki/tls/cert.pem'
                        - '-openshift-ca=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt'
                      env:
                        - name: HTTP_PROXY
                        - name: HTTPS_PROXY
                        - name: NO_PROXY
                      image: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:ef1882945053de37bdb0a8b86f3f3121e179a3c4880fb49d4d80793512c63b52
                      name: alertmanager-proxy
                      ports:
                        - containerPort: 9095
                          name: web
                          protocol: TCP
                      resources:
                        requests:
                          cpu: 1m
                          memory: 20Mi
                      terminationMessagePolicy: FallbackToLogsOnError
                      volumeMounts:
                        - mountPath: /etc/tls/private
                          name: secret-alertmanager-main-tls
                        - mountPath: /etc/proxy/secrets
                          name: secret-alertmanager-main-proxy
                        - mountPath: /etc/pki/ca-trust/extracted/pem/
                          name: alertmanager-trusted-ca-bundle
                          readOnly: true
                    - args:
                        - '--secure-listen-address=0.0.0.0:9092'
                        - '--upstream=http://127.0.0.1:9096'
                        - '--config-file=/etc/kube-rbac-proxy/config.yaml'
                        - '--tls-cert-file=/etc/tls/private/tls.crt'
                        - '--tls-private-key-file=/etc/tls/private/tls.key'
                        - '--tls-cipher-suites=TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305'
                        - '--logtostderr=true'
                        - '--v=10'
                      image: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:fec7471923a6869fca9beed9960ebeb968a14f0dd6e165a48541edce0b9a43db
                      name: kube-rbac-proxy
                      ports:
                        - containerPort: 9092
                          name: tenancy
                          protocol: TCP
                      resources:
                        requests:
                          cpu: 1m
                          memory: 15Mi
                      terminationMessagePolicy: FallbackToLogsOnError
                      volumeMounts:
                        - mountPath: /etc/kube-rbac-proxy
                          name: secret-alertmanager-kube-rbac-proxy
                        - mountPath: /etc/tls/private
                          name: secret-alertmanager-main-tls
                    - args:
                        - '--insecure-listen-address=127.0.0.1:9096'
                        - '--upstream=http://127.0.0.1:9093'
                        - '--label=namespace'
                      image: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:dbe6ed6fa700a81121a039fbd3648890579abd960757b673ae75b8a145a6a53e
                      name: prom-label-proxy
                      resources:
                        requests:
                          cpu: 1m
                          memory: 20Mi
                      terminationMessagePolicy: FallbackToLogsOnError
                    - name: config-reloader
                      resources:
                        requests:
                          cpu: 1m
                          memory: 10Mi
                  externalUrl: https://alertmanager-main-openshift-monitoring.apps.pm-demo.demo.red-chesterfield.com/
                  image: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:7b21960768ac11f6aae3afa98a92ee507268284b63226625b37a9850fc82c79f
                  listenLocal: true
                  nodeSelector:
                    kubernetes.io/os: linux
                  podMetadata:
                    annotations:
                      target.workload.openshift.io/management: '{"effect": "PreferredDuringScheduling"}'
                    labels:
                      app.kubernetes.io/component: alert-router
                      app.kubernetes.io/name: alertmanager
                      app.kubernetes.io/part-of: openshift-monitoring
                      app.kubernetes.io/version: 0.22.2
                  priorityClassName: system-cluster-critical
                  replicas: 3
                  resources:
                    requests:
                      cpu: 4m
                      memory: 40Mi
                  secrets:
                    - alertmanager-main-tls
                    - alertmanager-main-proxy
                    - alertmanager-kube-rbac-proxy
                  securityContext:
                    fsGroup: 65534
                    runAsNonRoot: true
                    runAsUser: 65534
                  serviceAccountName: alertmanager-main
                  version: 0.22.2
                  volumeMounts:
                    - mountPath: /etc/pki/ca-trust/extracted/pem/
                      name: alertmanager-trusted-ca-bundle
                      readOnly: true
                  volumes:
                    - configMap:
                        items:
                          - key: ca-bundle.crt
                            path: tls-ca-bundle.pem
                        name: alertmanager-trusted-ca-bundle-2rsonso43rc5p
                        optional: true
                      name: alertmanager-trusted-ca-bundle
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-policy-default-alertmanager
placementRef:
  name: placement-policy-default-alertmanager
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
  - name: policy-default-alertmanager
    kind: Policy
    apiGroup: policy.open-cluster-management.io
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-policy-default-alertmanager
spec:
  clusterConditions:
    - status: 'True'
      type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions: []

