apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-auto-controller
  annotations:
    policy.open-cluster-management.io/standards: NIST-CSF
    policy.open-cluster-management.io/categories: PR.IP Information Protection Processes and Procedures
    policy.open-cluster-management.io/controls: PR.IP-1 Baseline Configuration
spec:
  remediationAction: inform
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-auto-controller
        spec:
          remediationAction: inform
          severity: low
          namespaceSelector:
            exclude:
              - kube-*
            include:
              - default
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: automationcontroller.ansible.com/v1beta1
                kind: AutomationController
                metadata:
                  name: auto-controller
                  namespace: ansible-automation-platform
                spec:
                  admin_user: admin
                  create_preload_data: true
                  garbage_collect_secrets: false
                  image_pull_policy: IfNotPresent
                  ingress_type: Route
                  projects_persistence: false
                  replicas: 1
                  route_tls_termination_mechanism: Edge
                  task_privileged: false
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-policy-auto-controller
placementRef:
  name: placement-policy-auto-controller
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
  - name: policy-auto-controller
    kind: Policy
    apiGroup: policy.open-cluster-management.io
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-policy-auto-controller
spec:
  clusterConditions:
    - status: 'True'
      type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - key: environment
        operator: In
        values:
          - dev
