apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-poison-pill-config
  annotations:
    policy.open-cluster-management.io/standards: NIST-CSF
    policy.open-cluster-management.io/categories: PR.IP Information Protection Processes and Procedures
    policy.open-cluster-management.io/controls: PR.IP-1 Baseline Configuration
spec:
  remediationAction: inform
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-namespace-poison-pill
        spec:
          remediationAction: inform
          severity: low
          namespaceSelector:
            exclude:
              - kube-*
            include:
              - default
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Namespace
                metadata:
                  name: poison-pill
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-operatorgroup-poison-pill
        spec:
          remediationAction: inform
          severity: low
          namespaceSelector:
            exclude:
              - kube-*
            include:
              - default
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: operators.coreos.com/v1
                kind: OperatorGroup
                metadata:
                  name: poison-pill-manager
                  namespace: poison-pill
                spec:
                  targetNamespaces:
                    - poison-pill
                  name: poison-pill
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-subscription-poison-pill
        spec:
          remediationAction: inform
          severity: low
          namespaceSelector:
            exclude:
              - kube-*
            include:
              - default
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: operators.coreos.com/v1alpha1
                kind: Subscription
                metadata:
                    name: poison-pill-manager
                    namespace: poison-pill
                spec:
                    channel: alpha
                    name: poison-pill-manager
                    source: redhat-operators
                    sourceNamespace: openshift-marketplace
                    package: poison-pill-manager                
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-operatorgroup-poison-pill
        spec:
          remediationAction: inform
          severity: low
          namespaceSelector:
            exclude:
              - kube-*
            include:
              - default
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: poison-pill.medik8s.io/v1alpha1
                kind: PoisonPillConfig
                metadata:
                  name: poison-pill-config
                  namespace: openshift-operators
                spec:
                  safeTimeToAssumeNodeRebootedSeconds: 180
                  watchdogFilePath: /test/watchdog1
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-policy-poison-pill-config
placementRef:
  name: placement-policy-poison-pill-config
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
  - name: policy-poison-pill-config
    kind: Policy
    apiGroup: policy.open-cluster-management.io
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-policy-poison-pill-config
spec:
  clusterConditions:
    - status: 'True'
      type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - key: environment
        operator: In
        values:
          - dev
