apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-config-build
  namespace: default
  annotations:
    policy.open-cluster-management.io/standards: NIST-CSF
    policy.open-cluster-management.io/categories: PR.IP Information Protection Processes and Procedures
    policy.open-cluster-management.io/controls: PR.IP-1 Baseline Configuration
spec:
  remediationAction: inform
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-config-build
        spec:
          remediationAction: inform
          severity: low
          namespaceSelector:
            exclude:
              - kube-*
            include:
              - default
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: config.openshift.io/v1
                kind: Build
                metadata:
                  annotations:
                    include.release.openshift.io/ibm-cloud-managed: 'true'
                    include.release.openshift.io/self-managed-high-availability: 'true'
                    include.release.openshift.io/single-node-developer: 'true'
                    release.openshift.io/create-only: 'true'
                  name: cluster
                spec: {}
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-policy-config-build
  namespace: default
placementRef:
  name: placement-policy-config-build
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
  - name: policy-config-build
    kind: Policy
    apiGroup: policy.open-cluster-management.io
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-policy-config-build
  namespace: default
spec:
  clusterConditions:
    - status: 'True'
      type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - key: cloud
        operator: In
        values:
          - Amazon

