apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-config-gitops-cluster
  namespace: policy-openshift-gitops-operator
  annotations:
    policy.open-cluster-management.io/standards: NIST-CSF
    policy.open-cluster-management.io/categories: PR.IP Information Protection Processes and Procedures
    policy.open-cluster-management.io/controls: PR.IP-1 Baseline Configuration
spec:
  remediationAction: inform
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-gitops-cluster-prod-ns
        spec:
          remediationAction: inform
          severity: low
          namespaceSelector:
            exclude:
              - kube-*
            include:
              - default
          object-templates:
            - complianceType: musthave
              objectDefinition: 
                apiVersion: apps.open-cluster-management.io/v1beta1
                kind: GitOpsCluster
                metadata:
                  name: argo-acm-clusters-1
                  namespace: openshift-gitops
                spec:
                  argoServer:
                    cluster: christian
                    argoNamespace: openshift-gitops
                  placementRef:
                    kind: Placement
                    apiVersion: cluster.open-cluster-management.io/v1alpha1
                    name: local-cluster
                    namespace: openshift-gitops

    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-gitops-cluster-prod-ns
        spec:
          remediationAction: inform
          severity: low
          namespaceSelector:
            exclude:
              - kube-*
            include:
              - default
          object-templates:
            - complianceType: musthave
              objectDefinition: 
                apiVersion: cluster.open-cluster-management.io/v1alpha1
                kind: ManagedClusterSetBinding
                metadata:
                  name: all-clusters
                  namespace: openshift-gitops
                spec:
                  clusterSet: all-clusters
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-gitops-cluster-prod-ns
        spec:
          remediationAction: inform
          severity: low
          namespaceSelector:
            exclude:
              - kube-*
            include:
              - default
          object-templates:
            - complianceType: musthave
              objectDefinition: 
                apiVersion: cluster.open-cluster-management.io/v1alpha1
                kind: Placement
                metadata:
                  name: local-cluster
                  namespace: openshift-gitops
                spec:
                  clusterSets:
                    - all-clusters
                  predicates:
                    - requiredClusterSelector:
                        labelSelector:
                          matchExpressions:
                            - key: usage
                              operator: In
                              values:
                                - production
                                - development
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-policy-gitops-cluster
  namespace: policy-openshift-gitops-operator
placementRef:
  name: placement-policy-gitops-cluster
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
  - name: policy-gitops-cluster
    kind: Policy
    apiGroup: policy.open-cluster-management.io
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-policy-gitops-cluster
  namespace: policy-openshift-gitops-operator
spec:
  clusterConditions:
    - status: 'True'
      type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - key: cloud
        operator: In
        values:
          - Amazon
      - key: local-cluster
        operator: In
        values:
          - 'true'
