apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-config-clustersets
  namespace: policy-openshift-gitops-operator
  annotations:
    policy.open-cluster-management.io/standards: NIST, NIST-CSF
    policy.open-cluster-management.io/categories: PR.DS Data Security, PR.IP Information Protection Processes and Procedures
    policy.open-cluster-management.io/controls: PR.IP-1 Baseline Configuration
spec:
  remediationAction: inform
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-configure-managed-clustersets-prod-ns
        spec:
          remediationAction: inform
          severity: low
          namespaceSelector:
            exclude:
              - kube-*
            include:
              - default
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: cluster.open-cluster-management.io/v1beta1
                kind: ManagedClusterSet
                metadata:
                  name: clusterset1
            - complianceType: musthave
              objectDefinition:
                apiVersion: cluster.open-cluster-management.io/v1beta1
                kind: ManagedClusterSet
                metadata:
                  name: clusterset2
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-policy-config-clustersets
  namespace: policy-openshift-gitops-operator
placementRef:
  name: placement-policy-config-clustersets
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
  - name: policy-config-clustersets
    kind: Policy
    apiGroup: policy.open-cluster-management.io
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-policy-config-clustersets
  namespace: policy-openshift-gitops-operator
spec:
  clusterConditions:
    - status: 'True'
      type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - key: local-cluster
        operator: In
        values:
          - 'true'
