---
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sHttpsOnly
metadata:
  name: ingress-https-only
spec:
  informmentAction: dryrun
  match:
    kinds:
      - apiGroups: ["route.openshift.io"]
        kinds: ["Route"]
    excludedNamespaces: 
      - openshift-ingress-canary
